### ISSUE TITLE
Baldur's Gate Enchanced Edition

### ISSUE THREAD

**Issue by rtentser** [vv221/play.it#16] opened 2018-02-05 09:25 UTC
The game fails to start, i get an error:
./BaldursGate: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

libssl_1.0.0_32-bit.tar.gz is in the directory when i build a package.
libssl1.0.2 was installed from debian repository.

**Comment by vv221** [comment] 2018-02-05 18:45
Looks like a bug on our side, I’ll check the building process and report back here.

**Comment by vv221** [comment] 2018-02-05 18:59
Bug confirmed, I’m working on a fix.

**Comment by vv221** [comment] 2018-02-05 19:46
This is fixed in commit 577279209efbc88739aff0f50ebf917ce2cccd31

**Closed by vv221** 2018-02-05 19:46 UTC
Labels: bug

**Comment by rtentser** [comment] 2018-02-06 08:03
I tried new script. Same bug.

**Comment by vv221** [comment] 2018-02-06 20:12
You might need to delete the corrupted prefix generated by the previous script:
```
rm -Rf ~/.local/share/play.it/prefixes/baldurs-gate-enhanced-edition
```
Then just run the game again, no need to re-install it.
